In [1]:
#importing numpy library
import numpy as np

In [2]:
#creating numpy array from python_list
python_list=[2,4,6,8,10]
arr=np.array(python_list)
arr

array([ 2,  4,  6,  8, 10])

In [3]:
#function that will perform element wise addition on two lists
list_x=list(range(10000))
list_y=list(range(10000))
def list_sum():
    z=[]
    for i in range(len(list_x)):
        z.append(list_x[i]+list_y[i])

In [4]:
#function that will perform element wise addition on numpy arrays
arr_x=np.array(list_x)
arr_y=np.array(list_y)
def numpy_arr_sum():
    arr_z=arr_x+arr_y

In [5]:
#checking which is taking long time to execute
from timeit import Timer
timer_obj1=Timer("list_sum()","from __main__ import list_sum")
timer_obj2=Timer("numpy_arr_sum()","from __main__ import numpy_arr_sum")
print("Pure Python version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

Pure Python version: 5.547726
Numpy version: 0.013380299999999679


In [6]:
#attributes of a numpy array
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f"Shape of an array:{arr.shape}")
print(f"Size of an array:{arr.size}")
print(f"Type of an object:{type(arr)}")
print(f"Dimension of an array:{arr.ndim}")
print(f"Type of an array:{arr.dtype}")

Shape of an array:(4, 3)
Size of an array:12
Type of an object:<class 'numpy.ndarray'>
Dimension of an array:2
Type of an array:int32


In [7]:
#ways to create basic numpy arrays
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.arange(10)
arr3=np.ones((4,3))
arr4=np.zeros((4,3))
arr5=np.linspace(start=1,stop=10,num=5)

In [8]:
print("creating using python list:\n",arr1,'\n')
print("creating using arange function:\n",arr2,'\n')
print("creating using ones funtion:\n",arr3,'\n')
print("creating using zeros function:\n",arr4,'\n')
print("creating using linspace funtion:\n",arr5,'\n')

creating using python list:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

creating using arange function:
 [0 1 2 3 4 5 6 7 8 9] 

creating using ones funtion:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

creating using zeros function:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

creating using linspace funtion:
 [ 1.    3.25  5.5   7.75 10.  ] 



In [9]:
#adding an element to an array
arr=np.array([2,5,7,3,4,6])
print(np.append(arr,10))
#adding an element to the list
python_list.append(21)
print(python_list)
np.append(python_list,22) #this doesnt save until we save it in a new variable or assign back to the same variable

[ 2  5  7  3  4  6 10]
[2, 4, 6, 8, 10, 21]


array([ 2,  4,  6,  8, 10, 21, 22])

In [10]:
#deleting an element from an array
print(np.delete(arr,4))
#deleting an element from the list
np.delete(python_list,5)

[2 5 7 3 6]


array([ 2,  4,  6,  8, 10])

In [11]:
#sorting an array
print(np.sort(arr))
#sorting a python_list
np.sort(python_list) #result is a numpy array

[2 3 4 5 6 7]


array([ 2,  4,  6,  8, 10, 21])

In [12]:
#reshaping an array
arr=np.arange(24)
np.reshape(arr,(8,3))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
arr.reshape((2,12)) #we can use rehsape function directly on the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
#reshaping a list
l=[2,4,5,6,7,9]
np.reshape(l,(2,3))

array([[2, 4, 5],
       [6, 7, 9]])

In [15]:
#we cannot use append method directly on the array(we can use on the list) and we cannot use reshape method directly on the list(we can use on the array)

In [16]:
#indexing and slicing an array
#positive indexing
arr=np.array([2,3,5,6,4])
arr[2]

5

In [17]:
#list indexing
l1=[[2,4,5],[6,7,8,9]]
l1[0][0] #bracket difference

2

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
arr[0,1]

2

In [19]:
#slicing an array
arr[0,0:2]

array([1, 2])

In [20]:
#negative indexing
arr[-1]

array([4, 5, 6])

In [21]:
arr=np.arange(16)

In [22]:
arr=arr.reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
arr[-3:-1,-2:]

array([[ 6,  7],
       [10, 11]])

In [24]:
#striding
arr[0:3:2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])